```{r}
# Get the Data, Read in with tidytuesdayR package
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!
#tuesdata <- tidytuesdayR::tt_load('2021-03-16')
#tuesdata <- tidytuesdayR::tt_load(2021, week = 12)
#games <- tuesdata$games

# Or read in the data manually
games <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-16/games.csv')

#--------------------
library(tidyverse)
library(plotly)
library(lubridate)

#Explore data
head(games)
summary(games)

games %>% filter(year ==2020) %>% 
  group_by(gamename) %>% 
  summarize(monthlyavg = round(sum(avg)/12)) %>% 
  arrange(desc(monthlyavg))

#Final Fantasy games 
games %>% filter(grepl('Final', gamename, ignore.case = TRUE)) %>% 
  filter(!gamename=='The Final Station' ) %>%
  group_by(gamename, year) %>% 
  summarize(monthlyavg = round(sum(avg)/12)) %>% 
  arrange(desc(gamename,year))

games %>% filter(grepl('Final', gamename, ignore.case = TRUE)) %>%
  filter(!gamename=='The Final Station' ) %>%
  transmute(gamename,
            date = yearmonth(ymd(paste(year, month, "1"))),
            avg, peak, gain) -> games2

#Plot: Basic bubble chart
games2 %>%
  ggplot(aes(x=date, y=avg, size=avg, fill=gamename)) +
    geom_point(alpha=0.5, shape=21, color="black") + 
    scale_size(range = c(.1, 24)) +
    theme(legend.position="bottom") +
    theme_minimal() +
    labs(title = "Final Fantasy players on Steam over time",
        x = NULL,
        y = "Average number of players")

#Plot: Plotly interactive bubble chart
p <- plot_ly(games2, 
             x = ~as.Date(date, "%m/%d/%Y"), 
             y = ~avg, 
               text = ~gamename,
               type = 'scatter', mode = 'lines+markers', size = ~avg, 
               color= ~gamename, 
               colors = 'Paired',
        sizes = c(10,28),
        marker = list(opacity = 0.5, sizemode = 'diameter'))
p <- p %>% layout(title = 'Average number of Final Fantasy players on Steam',
         xaxis = list(title = 'Time',
                      showgrid = FALSE),
         yaxis = list(title = 'Average number of players', 
                      showgrid = FALSE))
         #,showlegend=FALSE)
p

htmlwidgets::saveWidget(p, "games.html")
```

```{r}
fig <- plot_ly(
  labels = c("Eve", "Cain", "Seth", "Enos", "Noam", "Abel", "Awan", "Enoch", "Azura"),
  parents = c("", "Eve", "Eve", "Seth", "Seth", "Eve", "Eve", "Awan", "Eve"),
  values = c(10, 14, 12, 10, 2, 6, 6, 4, 4),
  type = 'sunburst'
)

fig
```
